apiVersion: v1
kind: Secret
metadata:
  labels:
    argocd.argoproj.io/secret-type: cluster
    environment: ops
    enable_velero: 'true'
  annotations:
    aws_cluster_name: hub-cluster
    k8s_service_host: 23A8469AA66CA0034AE0296F01C6C988.gr7.us-east-1.eks.amazonaws.com
    velero_backup_s3_bucket_name: gitopscon-na-24-velero-backups-carlos-hub
    velero_iam_role_arn: arn:aws:iam::015299085168:role/velero-role-b2a6bda
    addons_repo_url: https://github.com/csantanapr/gitopscon-2024-na-demo
    addons_repo_revision: HEAD
    aws_region: us-east-1
    aws_account_id: '015299085168'
    velero_namespace: velero
    velero_service_account: velero
    velero_backup_s3_bucket_prefix: backups
  name: hub-cluster-secret
  namespace: argocd
type: Opaque
stringData:
  name: hub
  server: https://kubernetes.default.svc
data:
  config: ewogICJ0bHNDbGllbnRDb25maWciOiB7CiAgICAiaW5zZWN1cmUiOiBmYWxzZQogIH0KfQo=
